
GET http://localhost:3000/user

###

POST http://localhost:3000/user/create
Content-Type: application/json

{
    "name": "Frege3", "password": "password"

}

###

POST http://localhost:3000/user/login 
Content-Type: application/json

{
    "name": "Frege2", "password": "password"

}
